db.user.insertOne({
    "CreatedAt": new Date("2024-05-15T01:01:01.100Z"),
    "Email": "ttrasn@gmail.com",
    "Name": "Reza",
    "Password": "$2a$11$JVs2kBLZh.qoZg0Aot1t6euk4nIhf7L59GgRwfFtyfWP6D/VP34ra",
    "UpdatedAt": new Date("2024-05-15T01:01:01.100Z"),
    "UserType": 1
});


db.game.insertMany([{
    "Description": "Triple Edge Studios",
    "GameTitle": "Fire and Roses Joker™",
    "Genre": "Slots",
    "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/FireandRosesJoker/tile.webp",
    "Platform": "PlayStation",
    "Price": "32",
    "Rating": 1,
    "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
    "Status": 0,
    "StudioName": "Games Global",
    "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
    "Description": "Triple Edge Studios",
    "GameTitle": "Masks of Fire",
    "Genre": "Slots",
    "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/9MasksofFire/tile.webp",
    "Platform": "PlayStation",
    "Price": "32",
    "Rating": 1,
    "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
    "Status": 0,
    "StudioName": "Games Global",
    "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
}, {
    "Description": "Triple Edge Studios",
    "GameTitle": "Amazing Link Zeus",
    "Genre": "Slots",
    "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/AmazingLinkZeus/tile.webp",
    "Platform": "PlayStation",
    "Price": "32",
    "Rating": 1,
    "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
    "Status": 0,
    "StudioName": "Games Global",
    "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
    "Description": "Triple Edge Studios",
    "GameTitle": "Blazing Bison™ Gold Blitz™",
    "Genre": "Slots",
    "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/BlazingBisonGoldBlitz/tile.webp",
    "Platform": "PlayStation",
    "Price": "32",
    "Rating": 1,
    "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
    "Status": 0,
    "StudioName": "Games Global",
    "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
     "Description": "Triple Edge Studios",
     "GameTitle": "Ancient Fortunes: Poseidon™ WowPot! MEGAWAYS™",
     "Genre": "Slots",
     "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/AncientFortunesPoseidonWOWPotMegaways/tile.webp",
     "Platform": "PlayStation",
     "Price": "32",
     "Rating": 1,
     "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
     "Status": 0,
     "StudioName": "Games Global",
     "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
      "Description": "Triple Edge Studios",
      "GameTitle": "Area Link™ Phoenix",
      "Genre": "Slots",
      "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/AreaLinkPhoenix/tile.webp",
      "Platform": "PlayStation",
      "Price": "32",
      "Rating": 1,
      "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
      "Status": 0,
      "StudioName": "Games Global",
      "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
     "Description": "Triple Edge Studios",
     "GameTitle": "Immortal Romance Remastered",
     "Genre": "Slots",
     "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/ImmortalRomanceRemastered/tile.webp",
     "Platform": "PlayStation",
     "Price": "32",
     "Rating": 1,
     "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
     "Status": 0,
     "StudioName": "Games Global",
     "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
      "Description": "Triple Edge Studios",
      "GameTitle": "Gold Blitz Extreme™",
      "Genre": "Slots",
      "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/GoldBlitzExtreme/tile.webp",
      "Platform": "PlayStation",
      "Price": "32",
      "Rating": 1,
      "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
      "Status": 0,
      "StudioName": "Games Global",
      "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
      "Description": "Triple Edge Studios",
      "GameTitle": "Thunderstruck Wild Lightning",
      "Genre": "Slots",
      "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/ThunderstruckWildLightning/tile.webp",
      "Platform": "PlayStation",
      "Price": "32",
      "Rating": 1,
      "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
      "Status": 0,
      "StudioName": "Games Global",
      "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
      "Description": "Triple Edge Studios",
      "GameTitle": "Book of Oz",
      "Genre": "Slots",
      "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/BookofOz/tile.webp",
      "Platform": "PlayStation",
      "Price": "32",
      "Rating": 1,
      "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
      "Status": 0,
      "StudioName": "Games Global",
      "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
      "Description": "Triple Edge Studios",
      "GameTitle": "Sherlock and Moriarty WOWPOT",
      "Genre": "Slots",
      "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/SherlockMoriartyWOWPOT/tile.webp",
      "Platform": "PlayStation",
      "Price": "32",
      "Rating": 1,
      "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
      "Status": 0,
      "StudioName": "Games Global",
      "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
      "Description": "Triple Edge Studios",
      "GameTitle": "Gold Faactory Jackpots Mega Moolah",
      "Genre": "Slots",
      "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/GoldFactoryJackpotsMegaMoolah/tile.webp",
      "Platform": "PlayStation",
      "Price": "32",
      "Rating": 1,
      "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
      "Status": 0,
      "StudioName": "Games Global",
      "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
       "Description": "Triple Edge Studios",
       "GameTitle": "Book of Atem WowPot",
       "Genre": "Slots",
       "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/BookofAtemWOWPOT/tile.webp",
       "Platform": "PlayStation",
       "Price": "32",
       "Rating": 1,
       "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
       "Status": 0,
       "StudioName": "Games Global",
       "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
},{
        "Description": "Triple Edge Studios",
        "GameTitle": "Absolootly Mad Mega Moolah",
        "Genre": "Slots",
        "ImageUrl": "https://cdne-clientzone-prod-westeurope-001.azureedge.net/public/games/AbsolootlyMadMegaMoolah/tile.webp",
        "Platform": "PlayStation",
        "Price": "32",
        "Rating": 1,
        "ReleaseDate": new Date("2001-06-27T00:00:00.000Z"),
        "Status": 0,
        "StudioName": "Games Global",
        "UpdatedAt": new Date("2001-06-27T00:00:00.000Z")
}]);